title: " "
logo: https://raw.githubusercontent.com/xiranwang7/My-Website/master/xiran.jpg
 
description:  "  \"Your work is going to fill a large part of your life,
and the only way to be truly satisfied is to do what you believe is great work. 
And the only way to do great work is to love what you do.\" -Steve Jobs "
show_downloads: false
google_analytics:

theme: jekyll-theme-dinky
